package com.myopicmobile.textwarrior4.common;

public class LanguageHtml extends Language
{
    private static Language _theOne = null;

    private final static String[] keywords = {
            "h1",
        "h2",
        "h3",
        "h4",
        "h5",
        "h6",
        "head",
        "meta",
        "body",
        "DOCTYPE",
        "a",
        "abbr",
        "acronym",
        "address",
        "applet",
        "area",
        "article",
    "aside",
        "audio",
        "b",
        "base",
        "basefont",
        "bdi",
        "bdo",
        "big",
        "blockquote",
        "br",
        "button",
        "canvas",
        "caption",
        "center",
        "cite",
        "code",
        "col",
        "colgroup",
        "command",
        "datalist",
        "dd",
        "del",
        "details",
        "dfn",
        "dialog",
        "dir",
        "div",
        "dl",
        "dt",
        "em",
        "embed",
        "fieldset",
        "figcaption",
        "figure",
        "font",
        "footer",
        "form",
        "frame",
        "frameset",
        "header",
        "hr",
        "html",
        "i",
        "iframe",
        "img",
        "input",
        "ins",
        "kbd",
        "keygen",
        "label",
        "legend",
        "li",
        "link",
        "main",
        "map",
        "mark",
        "menu",
        "menuitem",
        "meta",
        "meter",
        "nav",
        "noframes",
        "noscript",
        "object",
        "ol",
        "optgroup",
        "option",
        "p",
        "param",
        "pre",
        "progress",
        "q",
        "rq",
        "rt",
        "ruby",
        "s",
        "samp",
        "script",
        "section",
        "select",
        "small",
        "source",
        "span",
        "strike",
        "strong",
        "style",
        "sub",
        "summary",
        "sup",
        "table",
        "tbody",
        "td",
        "textarea",
        "tfoot",
        "th",
        "thead",
        "time",
        "title",
        "tr",
        "track",
        "tt",
        "u",
        "ul",
        "var",
        "video",
        "wbr"
    };

    private final static String[] function = {
        "class",
        "id",
        "style",
        "title",
        "href",
        "src",
        "charset",
        "http-equiv",
        "name",
        "content",
        "lang",
        "size",
        "rel",
        "type",
        "shape",
        "coords",
        "border",
        "width",
        "colspan",
        "value",
        "height",
        "target",
        "frameborder",
        "onclick",
        "action",
        "method",
        "maxlength",
        "checked",
        "selected",
        "rows",
        "cols",
        "alt",
        "readonly",
        "disabled", 
    };

    

    public static Language getInstance() {
        if (_theOne == null) {
            _theOne = new LanguageHtml();
        }
        return _theOne;
    }

    private LanguageHtml() {
        //setOperators(BASIC_C_OPERATORS);
        setKeywords(keywords);
        setNames(function);
    }

    /**
     * Java has no preprocessors. Override base class implementation
     */
    public boolean isLineAStart(char c) {
        return false;
	}
}
